name: test (workflow_run)
on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed
jobs:
  server:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      issues: write
      actions: read
    steps:
      - run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJson(github.event) }}
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{github.event.workflow_run.id}}
          name: secure-action
          github-token: ${{ github.token }}
      - uses: szksh-lab/secure-action@latest
        id: prepare
        with:
          action: server/prepare

      - uses: szksh-lab/secure-action@latest
        with:
          action: server/apply
          ops: ${{ steps.prepare.outputs.ops }}
          github_token: ${{ github.token }}

      - if: failure() && steps.prepare.outputs.pull_request_number != ''
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.prepare.outputs.pull_request_number }}
          COMMENT: |
            [Workflow](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
        run: |
          gh pr comment \
            -R "$GITHUB_REPOSITORY" \
            -b "${COMMENT}" \
            "$PR_NUMBER"

