---
name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      issues: write
    steps:
      - uses: szksh-lab/secure-action@latest
        with:
          handler: secure-action/action:octokit/rest.js
          method: rest.issues.createLabel
          data: |
            owner: ${{github.event.repository.owner.login}}
            repo: ${{github.event.repository.name}}
            name: "test"
      - uses: szksh-lab/secure-action@latest
        with:
          action: trigger
          server_repository: test-secure-action
